server:
  port: 8005

spring:
  application:
  name: config-server
  profiles:
    active: native


eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



