  server:
    port: 8001


  eureka:
    client:
      enabled: true
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/


  management:
    tracing:
      sampling:
        probability: 1.0